[package]
name = "rup"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = 'abort'

[dependencies]
colorust = { git = "https://github.com/ntalbs/colorust.git" }

[dev-dependencies]
p-test = "1.0.2"
